<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- Entity Framework Core 8 -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>
        runtime; build; native; contentfiles; analyzers; buildtransitive
      </IncludeAssets>
    </PackageReference>

    <!-- PostgreSQL -->
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Npgsql" Version="8.0.6" />

    <!-- CAP 8 -->
    <PackageReference Include="DotNetCore.CAP" Version="8.4.1" />
    <PackageReference Include="DotNetCore.CAP.RabbitMQ" Version="8.4.1" />
    <PackageReference Include="DotNetCore.CAP.PostgreSql" Version="8.1.0" />

    <!-- Microsoft Extensions 8 -->
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.7" />

    <!-- JSON -->
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HR.Domain\HR.Domain.csproj" />
    <ProjectReference Include="..\HR.Shared\HR.Shared.csproj" />
  </ItemGroup>

</Project>