<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <!-- Microsoft Extensions 8 -->
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />

    <!-- PostgreSQL -->
    <PackageReference Include="Npgsql" Version="8.0.4" />

    <!-- CAP 8 -->
    <PackageReference Include="DotNetCore.CAP" Version="8.1.0" />
    <PackageReference Include="DotNetCore.CAP.RabbitMQ" Version="8.1.0" />
    <PackageReference Include="DotNetCore.CAP.PostgreSql" Version="8.1.0" />
  </ItemGroup>

</Project>