  trivy-image:
    name: Container Image Scan (Trivy Image)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Identity.Api Docker Image
        working-directory: ./Identity.Microservice/src/Identity.Api
        run: |
          docker build -t ums-identity-api:scan .

      - name: Run Trivy Image Scanner (Identity.Api)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'ums-identity-api:scan'
          format: 'table'
          output: 'trivy-image-identity.txt'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Upload Trivy Image results (Identity.Api)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-image-identity-results
          path: trivy-image-identity.txt
          retention-days: 30
